name: naivedhya
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  email_validator: ^3.0.0
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_core_web: ^2.24.1
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  google_maps_flutter: ^2.14.0
  google_sign_in: ^6.1.5
  image: ^4.5.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  path: ^1.9.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.0
  uuid: ^4.5.1
  fluttertoast: ^8.2.8 
  http: ^1.6.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env 
    - assets/Naivedhya_Logo/
    - assets/Google_Logo/
    - assets/Onboard_screen_images/
